import type { Metadata } from "next";
import { Vazirmatn, Inter } from "next/font/google";
import "@/app/styles/globals.css";

const vazirmatn = Vazirmatn({
  variable: "--font-vazirmatn",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["500"],
});

export const metadata: Metadata = {
  title: "Music App",
  description: "Generated by WebReactor",
};

export default function IntroLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${vazirmatn.variable} ${inter.variable}`}>
      <body>{children}</body>
    </html>
  );
}
